### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by yuri117** [AcroniTeam/AcroniWeb#1]
- [ ]  Página para download do Mobile

- [x] Carrinho de compras/checkout (cartão + boleto fake).
- [x] Inserir dado de desconto na conta do cliente e permitir usá-lo para deduzir o valor de uma compra no ato
- [ ] Teclado custom no carrinho
- [ ] Usuario premium na loja

**Comment by felipisan** [comment]
- Teclado custom no carrinho
- usuario premium na loja
